tr_platform_home:
    path:     /
    defaults: { 
        _controller: TRPlatformBundle:Platform:index }

tr_platform_irregular_verbs:
    path:     /irregular-verbs 
    defaults: {
        _controller: TRPlatformBundle:Platform:irregularVerbs }

tr_platform_exercice_a:
    path:     /exercice-1
    defaults: {
        _controller: TRPlatformBundle:Platform:exerciceA }