tr_platform_home:
    path:     /
    defaults: { 
        _controller: TRPlatformBundle:Platform:index }

tr_platform_irregular_verbs:
    path:     /irregular-verbs 
    defaults: {
        _controller: TRPlatformBundle:Platform:irregularVerbs }

tr_platform_exercice_a:
    path:     /exercice-1
    defaults: {
        _controller: TRPlatformBundle:Platform:exerciceA }

tr_platform_exercice_a_favorite:
    path:     /exercice-1/favorite
    defaults: {
        _controller: TRPlatformBundle:Platform:exerciceAFavorite }

tr_platform_admin_dashboard:
    path:     /admin/dashboard
    defaults: {
        _controller: TRPlatformBundle:Admin:dashboard }

tr_platform_admin_update_database:
    path:     /admin/update-database
    defaults: {
        _controller: TRPlatformBundle:Admin:updateDatabase }

tr_ajax_platform_vocabulary_favorite:
    path:     /ajax/vocabulary/favorite
    defaults: {
        _controller: TRPlatformBundle:Platform:ajaxfavorite }
