<?php

namespace TR\PlatformBundle\Repository;

/**
 * VocabularyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabularyRepository extends \Doctrine\ORM\EntityRepository
{
}
